### ISSUE TITLE
too few arguments to function ‘fts_mail_user_init’

### ISSUE THREAD

**Issue by kopspa** [grosjo/fts-xapian#164]
Hi

I can't compile with dovecot 2.3.21

fts-xapian-plugin.c: In function ‘fts_xapian_mail_user_created’:
fts-xapian-plugin.c:112:13: error: too few arguments to function ‘fts_mail_user_init’
  112 |         if (fts_mail_user_init(user, &error) < 0)
      |             ^~~~~~~~~~~~~~~~~~
In file included from fts-xapian-plugin.h:11,
                 from fts-xapian-plugin.c:4:
/root/dovecot-2.3.21/src/plugins/fts/fts-user.h:21:5: note: declared here
   21 | int fts_mail_user_init(struct mail_user *user, bool initialize_libfts,
      |     ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:562: fts-xapian-plugin.lo] Error 1
make[2]: Leaving directory '/root/1/fts-xapian/src'
make[1]: *** [Makefile:494: all-recursive] Error 1
make[1]: Leaving directory '/root/1/fts-xapian'
make: *** [Makefile:416: all] Error 2

can you help me?

thanks

**Comment by grosjo** [comment]
Are you doing :

autoreconf -vi --force
./configure --with-dovecot=/usr/lib/dovecot --YOUR-PARAMTER

**Comment by grosjo** [comment]
Kindly re-open if the problem is not solve
