### ISSUE TITLE
Build failing (1.2.8)

### ISSUE THREAD

**Issue by smtalk** [grosjo/fts-xapian#37]
1.2.8 fails to build with custom ICU location, 1.2.6 has no issues:
```fts-backend-xapian.cpp:9:28: fatal error: unicode/unistr.h: No such file or directory
 #include <unicode/unistr.h>
                            ^
compilation terminated.
make[2]: *** [fts-backend-xapian.lo] Error 1
make[2]: Leaving directory `/usr/local/directadmin/custombuild/fts-xapian-1.2.8/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/directadmin/custombuild/fts-xapian-1.2.8'
make: *** [all] Error 2```
