### ISSUE TITLE
Can't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by helmut72** [grosjo/fts-xapian#17]
I've tried to compile 1.0rc1 and current branch on Ubuntu 18.04, but get this error:
```
In file included from fts-backend-xapian.cpp:45:0:
fts-backend-xapian-functions.cpp: In function ‘void fts_backend_xapian_oldbox(xapian_fts_backend*)’:
fts-backend-xapian-functions.cpp:471:10: error: ‘gettimeofday’ was not declared in this scope
          gettimeofday(&tp, NULL);
          ^~~~~~~~~~~~
```

The steps I made:
```
apt build-dep dovecot-core
apt install git dovecot-dev libicu-dev libxapian-dev
autoreconf -vi
PANDOC=false ./configure --with-dovecot=/usr/lib/dovecot
```

**Comment by helmut72** [comment]
Sorry, my fault. I need to use the 2.3 packages from this repository:
https://repo.dovecot.org

Now it compiles.

**Comment by grosjo** [comment]
I added a call to #include <sys/time.h> in the .cpp file

**Comment by helmut72** [comment]
Ok, but it was completely my fault: I thought Ubuntu 18.04 comes with Dovecot 2.3, but it's 2.2

After installing Dovecot 2.3, your plugin compiles and it works well. Search is now a lot faster 👍 

Thanks for this great plugin!
